version: '3.1'

services:
    kanboard:
      image: kanboard/kanboard:latest
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - kanboard_data:/var/www/app/data
        - kanboard_plugins:/var/www/app/plugins
        - kanboard_ssl:/etc/nginx/ssl
      environment:
        DATABASE_URL: mysql://kanboard:kanboard-secret@db/kanboard
      depends_on: 
        - db

    db:
      image: mariadb:latest
      command: --default-authentication-plugin=mysql_native_password
      volumes: 
        - db_data:/var/lib/mysql/data
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: kanboard
        MYSQL_USER: kanboard
        MYSQL_PASSWORD: kanboard-secret

volumes:
    kanboard_data:
    kanboard_plugins:
    kanboard_ssl:
    db_data: